# Generated by Django 6.0.2 on 2026-02-21 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Conversation title/topic', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether conversation is still active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assistant Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant')], help_text='Message sender role', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='List of tools used to generate this response')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tool name (must match Python function name)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Tool description')),
                ('category', models.CharField(help_text="Tool category (e.g., 'calculation', 'analysis', 'recommendation')", max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Tool parameters schema')),
                ('is_active', models.BooleanField(default=True, help_text='Whether tool is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('summary', 'Health Summary'), ('recommendation', 'Wellness Recommendation'), ('alert', 'Health Alert'), ('pattern', 'Pattern Analysis'), ('trend', 'Trend Analysis')], help_text='Type of insight', max_length=20)),
                ('title', models.CharField(help_text='Insight title', max_length=255)),
                ('content', models.TextField(help_text='Detailed insight content')),
                ('related_metrics', models.JSONField(blank=True, default=list, help_text='Health metrics relevant to this insight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this insight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Health Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
