# Generated by Django 6.0.2 on 2026-02-21 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='customtool',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='healthinsight',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='healthinsight',
            name='related_metrics',
        ),
        migrations.AlterField(
            model_name='healthinsight',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='healthinsight',
            name='insight_type',
            field=models.CharField(choices=[('summary', 'Health Summary'), ('recommendation', 'Recommendation'), ('alert', 'Health Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthinsight',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthinsight',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='healthinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AssistantConversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
        migrations.DeleteModel(
            name='CustomTool',
        ),
    ]
