# Generated by Django 6.0.2 on 2026-02-22 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('basal_body_temperature', models.FloatField(blank=True, help_text='Body temperature at complete rest (°C/°F)', null=True)),
                ('blood_glucose', models.FloatField(blank=True, help_text='Blood sugar levels (mg/dL or mmol/L)', null=True)),
                ('blood_pressure_systolic', models.FloatField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.FloatField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True)),
                ('body_temperature', models.FloatField(blank=True, help_text='Current body temperature (°C/°F)', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Current pulse rate (bpm)', null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, help_text='Blood oxygen level SpO2 (percentage)', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breathing rate per minute', null=True)),
                ('resting_heart_rate', models.IntegerField(blank=True, help_text='Heart rate when at complete rest (bpm)', null=True)),
                ('vo2_max', models.FloatField(blank=True, help_text='Maximum oxygen consumption during exercise (mL/(kg·min))', null=True)),
            ],
            options={
                'verbose_name_plural': 'Vital Signs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FitnessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_calories_burned', models.FloatField(blank=True, help_text='Calories burned during activity (kcal)', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Travel distance during activities (km/miles)', null=True)),
                ('elevation_gained', models.FloatField(blank=True, help_text='Vertical distance climbed (m/ft)', null=True)),
                ('exercise_duration', models.IntegerField(blank=True, help_text='Duration of exercise session (minutes)', null=True)),
                ('exercise_type', models.CharField(blank=True, help_text='Type of exercise (e.g., Running, Walking, Cycling)', max_length=100, null=True)),
                ('floors_climbed', models.IntegerField(blank=True, help_text='Number of floors/stories climbed', null=True)),
                ('power', models.FloatField(blank=True, help_text='Exercise power output (watts)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Movement velocity (km/h or mph)', null=True)),
                ('steps', models.IntegerField(blank=True, help_text='Step count', null=True)),
                ('steps_cadence', models.FloatField(blank=True, help_text='Steps per minute rate (steps/min)', null=True)),
                ('total_calories_burned', models.FloatField(blank=True, help_text='Complete calorie expenditure (kcal)', null=True)),
                ('wheelchair_pushes', models.IntegerField(blank=True, help_text='Push count for wheelchair users', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fitness Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hydration', models.FloatField(blank=True, help_text='Water/fluid intake (mL/oz)', null=True)),
                ('protein', models.FloatField(blank=True, help_text='Protein intake (grams)', null=True)),
                ('carbohydrates', models.FloatField(blank=True, help_text='Carbohydrate intake (grams)', null=True)),
                ('fats', models.FloatField(blank=True, help_text='Fat intake (grams)', null=True)),
                ('calories', models.FloatField(blank=True, help_text='Total calorie intake (kcal)', null=True)),
                ('fiber', models.FloatField(blank=True, help_text='Fiber intake (grams)', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='Sodium intake (mg)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about meals/nutrition', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nutrition Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('basal_metabolic_rate', models.FloatField(blank=True, help_text='Calories burned at rest (kcal/day)', null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, help_text='Body fat percentage (%)', null=True)),
                ('bone_mass', models.FloatField(blank=True, help_text='Skeletal weight (kg/lb)', null=True)),
                ('height', models.FloatField(blank=True, help_text='Body height measurement (cm/in)', null=True)),
                ('lean_body_mass', models.FloatField(blank=True, help_text='Body weight minus fat mass (kg/lb)', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Body weight measurement (kg/lb)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Physical Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReproductiveHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, help_text='Date of the reproductive health data', null=True)),
                ('cervical_mucus', models.CharField(blank=True, choices=[('dry', 'Dry'), ('sticky', 'Sticky'), ('creamy', 'Creamy'), ('watery', 'Watery'), ('egg_white', 'Egg White')], help_text='Cervical fluid characteristics', max_length=20, null=True)),
                ('menstruation_flow', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], help_text='Period flow intensity', max_length=20, null=True)),
                ('menstruation_period_start', models.DateField(blank=True, help_text='Start date of menstrual cycle', null=True)),
                ('menstruation_period_end', models.DateField(blank=True, help_text='End date of menstrual cycle', null=True)),
                ('ovulation_test', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('indeterminate', 'Indeterminate')], help_text='Ovulation predictor test results', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about reproductive health', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_health', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reproductive Health',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, help_text='Date of sleep session', null=True)),
                ('sleep_duration', models.IntegerField(blank=True, help_text='Duration of sleep (minutes)', null=True)),
                ('sleep_start_time', models.TimeField(blank=True, help_text='Time when sleep started', null=True)),
                ('sleep_end_time', models.TimeField(blank=True, help_text='Time when sleep ended', null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], help_text='Subjective assessment of sleep quality', max_length=20, null=True)),
                ('deep_sleep_duration', models.IntegerField(blank=True, help_text='Duration of deep sleep (minutes)', null=True)),
                ('light_sleep_duration', models.IntegerField(blank=True, help_text='Duration of light sleep (minutes)', null=True)),
                ('rem_sleep_duration', models.IntegerField(blank=True, help_text='Duration of REM sleep (minutes)', null=True)),
                ('awake_duration', models.IntegerField(blank=True, help_text='Duration awake during sleep session (minutes)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about sleep (e.g., disturbances)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sleep Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
