# Generated by Django 6.0.2 on 2026-02-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healix_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
