# Generated by Django 6.0.2 on 2026-02-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healix_server', '0002_alter_vitalsigns_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
