# Generated by Django 6.0.2 on 2026-02-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healix_server', '0003_alter_vitalsigns_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
