# Generated by Django 6.0.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healix_server', '0004_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts'),
            preserve_default=False,
        ),
    ]
